# ROOT must be set first
TARGET = libclient.a
#ROOT = $(BRU_BASE_PATH)/$(NAME)

# Headers path
CFLAGS += -I$(BRU_BASE_PATH)/core/include

# all .c files under
#$(NAME)SRCS = $(shell find $(ROOT) -type f -name "*\.c")

# u can set manually here
SRCS = ./main.c

