# ROOT must be set first
TARGET = libcore.a
#ROOT = $(BRU_BASE_PATH)/$(NAME)

# Headers path

# all .c files under
#$(NAME)SRCS = $(shell find $(ROOT) -type f -name "*\.c")

# u can set manually here
SRCS = main.c
